#!/bin/bash
# Do not need above shebang here, but isn't going to break anything

# Aliases that enable colour
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ls aliases (these inherit --color=auto from above)
alias l='ls -CF'

# Custom ll function
ll() {
    # Default to current directory if no argument provided
    local ARG="${1:-.}"
    { echo -ne "\033[1;35mMODE # OWNER GROUP SIZE MOD-TIMESTAMP NAME\033[0m\n-> -> -> "; \
      ls -lvh --color=always --group-directories-first --time-style="+%Y-%m-%d｜%H:%M:%S" "$ARG"
    } | column -t -R 2,3,4,5
}

# Custom la function
la() {
    # Default to current directory if no argument provided
    local ARG="${1:-.}"
    { echo -ne "\033[1;35mMODE # OWNER GROUP SIZE MOD-TIMESTAMP NAME\033[0m\n-> -> -> "; \
      ls -lAvh --color=always --group-directories-first --time-style="+%Y-%m-%d｜%H:%M:%S" "$ARG"
    } | column -t -R 2,3,4,5
}
