#!/bin/bash

# Aliases that enable colour
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ls aliases (these inherit --color=auto from above)
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
