#!/bin/bash
# Do not need above shebang here, but isn't going to break anything

# Space after makes bash check for (more) aliases after command
alias sudo='sudo '

# Aliases that enable colour
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='grep -F --color=auto'
alias egrep='grep -E --color=auto'
