#!/bin/sh
# Do not need above shebang for .profile (ignored by source command)
# But do need full POSIX compliance here hence sh not bash

# ~/.profile: executed by the command interpreter for login shells.
# If ~/.bash_profile or ~/.bash_login exist, bash(1) will read these
# instead of ~/.profile.
# See /usr/share/doc/bash/examples/startup-files for examples.
# The files are located in the bash-doc package.

# The default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# Set PATH so it includes this private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
    case ":$PATH:" in
        *":$HOME/.local/bin:"*) 
            ;; # private bin is already in PATH, do nothing
        *) 
            PATH="$HOME/.local/bin:$PATH" 
            ;; # private bin is missing from PATH, prepend it
    esac
fi

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# On WSL2 with systemd running only
# Pull variables loaded by /etc/environment.d into Windows Terminal
if [ -d /run/WSL ] && command -v systemctl > /dev/null 2>&1; then
    if env_vars=$(
        systemctl --user show-environment --no-pager 2> /dev/null
    ); then
        while IFS= read -r line; do
            export "${line?}"
        done << EOF
$env_vars
EOF
    fi
fi

# Plasma on WSL2 config moves WSLg to X1, with KWin XWayland on X0
if [ "${KDE_FULL_SESSION}" != "true" ] &&
   [ -L /tmp/.X11-unix/X1 ] &&
   [ "$(readlink /tmp/.X11-unix/X1)" = "/mnt/wslg/.X11-unix/X0" ]; then
    export DISPLAY=:1
fi
