[automount]
enabled=true
mountFsTab=false

[network]
generateHosts=true
generateResolvConf=true
hostname=WSL2Debian

[interop]
enabled=true
appendWindowsPath=false

[user]
default=phil

[boot]
systemd=true

[gpu]
enabled=true

[time]
useWindowsTimezone=true
